package live

const (
	inlineKeyboardTimes             = "Time"
	inlineKeyboardBestLap           = "Best Lap"
	inlineKeyboardBestLapSectors    = "Sectors BL."
	inlineKeyboardLastLap           = "Last Lap"
	inlineKeyboardLastLapSectors    = "Sectors LL."
	inlineKeyboardOptimumLap        = "Optimal"
	inlineKeyboardOptimumLapSectors = "Sectors O."
	inlineKeyboardSectors           = "Sectors"
	inlineKeyboardLiveMap           = "Map 🗺️"
	inlineKeyboardStatus            = "Status 🏎️"
	inlineKeyboardInfo              = "Info 👐"
	inlineKeyboardDiff              = "Gap ⏳"
	inlineKeyboardCompound          = "Tyres"
	inlineKeyboardLaps              = "Laps"
	inlineKeyboardTeam              = "Cars"
	inlineKeyboardDriver            = "Drivers"
	inlineKeyboardUpdate            = "Update"
	inlineKeyboardMaxSpeed          = "Top Speed"
	inlineKeyboardCar               = "Car"

	symbolTimes    = "⏱"
	symbolSectors  = "🔂"
	symbolCompound = "🛞"
	symbolLaps     = "🏁"
	symbolTeam     = "🏎️"
	symbolDriver   = "👐"
	symbolUpdate   = "🔄"
	symbolDiff     = "⏲️"
	symbolOptimum  = "🚀"
	symbolPhoto    = "📸"
)
